┌ Info
│ Run ['python', 'solutions/bytecoder.py', 'info']
│ Out
│ bytecoder
│ 1.0
│ The Rice Theorem Cookers
│ syntatic,python
│ macOS-15.6.1-x86_64-i386-64bit-Mach-O
│ Done 0
│ - group: The Rice Theorem Cookers
│ - name: bytecoder
│ - system: macOS-15.6.1-x86_64-i386-64bit-Mach-O
│ - tags: ['syntatic', 'python']
│ - version: 1.0
└ Info
┌ Case jpamb.cases.Arrays.arrayContent:()V
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Arrays.arrayContent:()V']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:Found it
│ Out
│ assertion error;80%
│ Done 0
│ - assertion error: 80.00% 1.50
│ Score 0.60
└ Case jpamb.cases.Arrays.arrayContent:()V
┌ Case jpamb.cases.Arrays.arrayInBounds:()V
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Arrays.arrayInBounds:()V']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:did not find it
│ Out
│ assertion error;20%
│ Done 0
│ - assertion error: 20.00% -1.50
│ Score 0.60
└ Case jpamb.cases.Arrays.arrayInBounds:()V
┌ Case jpamb.cases.Arrays.arrayIsNull:()V
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Arrays.arrayIsNull:()V']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:did not find it
│ Out
│ assertion error;20%
│ Done 0
│ - assertion error: 20.00% -1.50
│ Score 0.60
└ Case jpamb.cases.Arrays.arrayIsNull:()V
┌ Case jpamb.cases.Arrays.arrayIsNullLength:()V
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Arrays.arrayIsNullLength:()V']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:Found it
│ Out
│ assertion error;80%
│ Done 0
│ - assertion error: 80.00% 1.50
│ Score -1.50
└ Case jpamb.cases.Arrays.arrayIsNullLength:()V
┌ Case jpamb.cases.Arrays.arrayLength:()V
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Arrays.arrayLength:()V']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:Found it
│ Out
│ assertion error;80%
│ Done 0
│ - assertion error: 80.00% 1.50
│ Score -1.50
└ Case jpamb.cases.Arrays.arrayLength:()V
┌ Case jpamb.cases.Arrays.arrayNotEmpty:([I)V
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Arrays.arrayNotEmpty:([I)V']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:Found it
│ Out
│ assertion error;80%
│ Done 0
│ - assertion error: 80.00% 1.50
│ Score 0.60
└ Case jpamb.cases.Arrays.arrayNotEmpty:([I)V
┌ Case jpamb.cases.Arrays.arrayOutOfBounds:()V
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Arrays.arrayOutOfBounds:()V']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:did not find it
│ Out
│ assertion error;20%
│ Done 0
│ - assertion error: 20.00% -1.50
│ Score 0.60
└ Case jpamb.cases.Arrays.arrayOutOfBounds:()V
┌ Case jpamb.cases.Arrays.arraySometimesNull:(I)V
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Arrays.arraySometimesNull:(I)V']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:did not find it
│ Out
│ assertion error;20%
│ Done 0
│ - assertion error: 20.00% -1.50
│ Score 0.60
└ Case jpamb.cases.Arrays.arraySometimesNull:(I)V
┌ Case jpamb.cases.Arrays.arraySpellsHello:([C)V
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Arrays.arraySpellsHello:([C)V']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:Found it
│ Out
│ assertion error;80%
│ Done 0
│ - assertion error: 80.00% 1.50
│ Score 0.60
└ Case jpamb.cases.Arrays.arraySpellsHello:([C)V
┌ Case jpamb.cases.Arrays.arraySumIsLarge:([I)V
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Arrays.arraySumIsLarge:([I)V']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:Found it
│ Out
│ assertion error;80%
│ Done 0
│ - assertion error: 80.00% 1.50
│ Score 0.60
└ Case jpamb.cases.Arrays.arraySumIsLarge:([I)V
┌ Case jpamb.cases.Arrays.binarySearch:(I)V
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Arrays.binarySearch:(I)V']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:Found it
│ Out
│ assertion error;80%
│ Done 0
│ - assertion error: 80.00% 1.50
│ Score 0.60
└ Case jpamb.cases.Arrays.binarySearch:(I)V
┌ Case jpamb.cases.Calls.allPrimesArePositive:(I)V
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Calls.allPrimesArePositive:(I)V']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:Found it
│ Out
│ assertion error;80%
│ Done 0
│ - assertion error: 80.00% 1.50
│ Score 0.60
└ Case jpamb.cases.Calls.allPrimesArePositive:(I)V
┌ Case jpamb.cases.Calls.callsAssertFalse:()V
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Calls.callsAssertFalse:()V']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:did not find it
│ Out
│ assertion error;20%
│ Done 0
│ - assertion error: 20.00% -1.50
│ Score -1.50
└ Case jpamb.cases.Calls.callsAssertFalse:()V
┌ Case jpamb.cases.Calls.callsAssertFib:(I)V
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Calls.callsAssertFib:(I)V']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:Found it
│ Out
│ assertion error;80%
│ Done 0
│ - assertion error: 80.00% 1.50
│ Score 0.60
└ Case jpamb.cases.Calls.callsAssertFib:(I)V
┌ Case jpamb.cases.Calls.callsAssertIf:(Z)V
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Calls.callsAssertIf:(Z)V']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:did not find it
│ Out
│ assertion error;20%
│ Done 0
│ - assertion error: 20.00% -1.50
│ Score -1.50
└ Case jpamb.cases.Calls.callsAssertIf:(Z)V
┌ Case jpamb.cases.Calls.callsAssertIfWithTrue:()V
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Calls.callsAssertIfWithTrue:()V']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:did not find it
│ Out
│ assertion error;20%
│ Done 0
│ - assertion error: 20.00% -1.50
│ Score 0.60
└ Case jpamb.cases.Calls.callsAssertIfWithTrue:()V
┌ Case jpamb.cases.Calls.callsAssertTrue:()V
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Calls.callsAssertTrue:()V']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:did not find it
│ Out
│ assertion error;20%
│ Done 0
│ - assertion error: 20.00% -1.50
│ Score 0.60
└ Case jpamb.cases.Calls.callsAssertTrue:()V
┌ Case jpamb.cases.Loops.forever:()V
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Loops.forever:()V']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:did not find it
│ Out
│ assertion error;20%
│ Done 0
│ - assertion error: 20.00% -1.50
│ Score 0.60
└ Case jpamb.cases.Loops.forever:()V
┌ Case jpamb.cases.Loops.neverAsserts:()V
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Loops.neverAsserts:()V']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:Found it
│ Out
│ assertion error;80%
│ Done 0
│ - assertion error: 80.00% 1.50
│ Score -1.50
└ Case jpamb.cases.Loops.neverAsserts:()V
┌ Case jpamb.cases.Loops.neverDivides:()I
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Loops.neverDivides:()I']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:did not find it
│ Out
│ assertion error;20%
│ Done 0
│ - assertion error: 20.00% -1.50
│ Score 0.60
└ Case jpamb.cases.Loops.neverDivides:()I
┌ Case jpamb.cases.Loops.terminates:()V
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Loops.terminates:()V']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:Found it
│ Out
│ assertion error;80%
│ Done 0
│ - assertion error: 80.00% 1.50
│ Score 0.60
└ Case jpamb.cases.Loops.terminates:()V
┌ Case jpamb.cases.Simple.assertBoolean:(Z)V
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Simple.assertBoolean:(Z)V']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:Found it
│ Out
│ assertion error;80%
│ Done 0
│ - assertion error: 80.00% 1.50
│ Score 0.60
└ Case jpamb.cases.Simple.assertBoolean:(Z)V
┌ Case jpamb.cases.Simple.assertFalse:()V
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Simple.assertFalse:()V']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:Found it
│ Out
│ assertion error;80%
│ Done 0
│ - assertion error: 80.00% 1.50
│ Score 0.60
└ Case jpamb.cases.Simple.assertFalse:()V
┌ Case jpamb.cases.Simple.assertInteger:(I)V
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Simple.assertInteger:(I)V']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:Found it
│ Out
│ assertion error;80%
│ Done 0
│ - assertion error: 80.00% 1.50
│ Score 0.60
└ Case jpamb.cases.Simple.assertInteger:(I)V
┌ Case jpamb.cases.Simple.assertPositive:(I)V
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Simple.assertPositive:(I)V']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:Found it
│ Out
│ assertion error;80%
│ Done 0
│ - assertion error: 80.00% 1.50
│ Score 0.60
└ Case jpamb.cases.Simple.assertPositive:(I)V
┌ Case jpamb.cases.Simple.checkBeforeAssert:(I)V
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Simple.checkBeforeAssert:(I)V']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:Found it
│ Out
│ assertion error;80%
│ Done 0
│ - assertion error: 80.00% 1.50
│ Score 0.60
└ Case jpamb.cases.Simple.checkBeforeAssert:(I)V
┌ Case jpamb.cases.Simple.checkBeforeDivideByN2:(I)I
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Simple.checkBeforeDivideByN2:(I)I']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:Found it
│ Out
│ assertion error;80%
│ Done 0
│ - assertion error: 80.00% 1.50
│ Score -1.50
└ Case jpamb.cases.Simple.checkBeforeDivideByN2:(I)I
┌ Case jpamb.cases.Simple.checkBeforeDivideByN:(I)I
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Simple.checkBeforeDivideByN:(I)I']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:Found it
│ Out
│ assertion error;80%
│ Done 0
│ - assertion error: 80.00% 1.50
│ Score 0.60
└ Case jpamb.cases.Simple.checkBeforeDivideByN:(I)I
┌ Case jpamb.cases.Simple.divideByN:(I)I
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Simple.divideByN:(I)I']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:did not find it
│ Out
│ assertion error;20%
│ Done 0
│ - assertion error: 20.00% -1.50
│ Score 0.60
└ Case jpamb.cases.Simple.divideByN:(I)I
┌ Case jpamb.cases.Simple.divideByNMinus10054203:(I)I
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Simple.divideByNMinus10054203:(I)I']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:did not find it
│ Out
│ assertion error;20%
│ Done 0
│ - assertion error: 20.00% -1.50
│ Score 0.60
└ Case jpamb.cases.Simple.divideByNMinus10054203:(I)I
┌ Case jpamb.cases.Simple.divideByZero:()I
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Simple.divideByZero:()I']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:did not find it
│ Out
│ assertion error;20%
│ Done 0
│ - assertion error: 20.00% -1.50
│ Score 0.60
└ Case jpamb.cases.Simple.divideByZero:()I
┌ Case jpamb.cases.Simple.divideZeroByZero:(II)I
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Simple.divideZeroByZero:(II)I']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:did not find it
│ Out
│ assertion error;20%
│ Done 0
│ - assertion error: 20.00% -1.50
│ Score 0.60
└ Case jpamb.cases.Simple.divideZeroByZero:(II)I
┌ Case jpamb.cases.Simple.earlyReturn:()I
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Simple.earlyReturn:()I']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:did not find it
│ Out
│ assertion error;20%
│ Done 0
│ - assertion error: 20.00% -1.50
│ Score 0.60
└ Case jpamb.cases.Simple.earlyReturn:()I
┌ Case jpamb.cases.Simple.justReturn:()I
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Simple.justReturn:()I']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:did not find it
│ Out
│ assertion error;20%
│ Done 0
│ - assertion error: 20.00% -1.50
│ Score 0.60
└ Case jpamb.cases.Simple.justReturn:()I
┌ Case jpamb.cases.Simple.justReturnNothing:()V
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Simple.justReturnNothing:()V']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:did not find it
│ Out
│ assertion error;20%
│ Done 0
│ - assertion error: 20.00% -1.50
│ Score 0.60
└ Case jpamb.cases.Simple.justReturnNothing:()V
┌ Case jpamb.cases.Simple.multiError:(Z)I
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Simple.multiError:(Z)I']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:Found it
│ Out
│ assertion error;80%
│ Done 0
│ - assertion error: 80.00% 1.50
│ Score 0.60
└ Case jpamb.cases.Simple.multiError:(Z)I
┌ Case jpamb.cases.Tricky.collatz:(I)V
│ Run ['python', 'solutions/bytecoder.py', 'jpamb.cases.Tricky.collatz:(I)V']
DEBUG:root:check assertion
DEBUG:root:read the method name
DEBUG:root:looking up method
DEBUG:root:trying to find an assertion error being created
DEBUG:root:Found it
│ Out
│ assertion error;80%
│ Done 0
│ - assertion error: 80.00% 1.50
│ Score 0.60
└ Case jpamb.cases.Tricky.collatz:(I)V
Total 9.60
